server:
  port: 1234

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate 

    datasource:
        url: jdbc:mysql://localhost/prueba
        username: root
        password: aguilar
        driver-class-name: com.mysql.jdbc.Driver