server:
  port: 8080

spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://localhost/prueba
        username: root
        password: aguilar
        driver-class-name: com.mysql.jdbc.Driver